dhcp_global_default_lease_time: 28800   # 8hrs
  dhcp_global_max_lease_time: 43200       # 12 hrs
  dhcp_global_subnet_mask: 255.255.255.0
  dhcp_global_broadcast_address: 192.168.222.255
  # dhcp_global_routers: 10.0.2.2
  dhcp_global_domain_name: wizznet.co.uk
  dhcp_global_domain_name_servers:
    - 10.22.66.5
    - 10.21.66.5
    - 10.20.66.5
    - 1.1.1.1
    - 9.9.9.9
    - 8.8.8.8
    - 8.8.4.4
  dhcp_global_bootp: allow
  dhcp_global_booting: allow
  dhcp_global_next_server: 192.168.222.3
  dhcp_global_filename: boot.img
  dhcp_subnets:
    - ip: 10.100.0.0
      netmask: 255.255.255.0
      domain_name_servers:
        - 10.22.66.5
        - 10.21.66.5
        - 10.20.66.5
        - 1.1.1.1
        - 9.9.9.9
      range_begin: 10.100.0.115
      range_end: 10.100.0.175
      routers: 10.100.0.1
  #    pools:
  #      - default_lease_time: 1800
  #        max_lease_time: 3600
  #        range_begin: 192.168.222.101
  #        range_end: 192.168.222.127
  #        allow: 'members of "vbox"'
    - ip: 10.101.0.0
      default_lease_time: 3600
      max_lease_time: 7200
      netmask: 255.255.255.0
      domain_name_servers:
        - 10.22.66.5
        - 10.21.66.5
        - 10.20.66.5
        - 1.1.1.1
        - 9.9.9.9
      routers: 10.101.0.1

#  dhcp_hosts:
#    - name: cl1
#      mac: 'de:ad:c0:de:ca:fe'
#      ip: 192.168.222.150
#    - name: cl2
#      mac: '00:de:ad:be:ef:00'
#      ip: 192.168.222.151
#  dhcp6_enable: true
#  dhcp6_subnets:
#    - ip: 'fdad:d155:f869:55b4::'
#      cidr: 64
#      range_begin: 'fdad:d155:f869:55b4::2:0000'
#      range_end: 'fdad:d155:f869:55b4::2:ffff'
#      default_lease_time: 1800
#      max_lease_time: 7200
#      hosts:
#        - name: testws
#          mac: '08:00:27:4c:e4:46'
#          ip: 'fdad:d155:f869:55b4::3:1'