
- name: install cake qos systemd unit file
  ansible.builtin.template:
    src: systemd/interface.service.j2
    dest: "/etc/systemd/system/cake-{{item.name}}.service"
  loop: "{{ interfaces.bridges.container_bridges }}"


- name: Start cake qos service
  systemd:
    name: "cake-{{item.name}}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ interfaces.bridges.container_bridges }}"