# initial reboot
#- include_role:
#    name: common
#    tasks_from: reboot

- name: check existence of files - frr
  stat:
    path: /etc/frr/frr.conf
  register: frr
  tags: ['always']
  ignore_errors: true
  
- name: check existence of files - ifupdown2
  stat:
    path: /etc/network/interfaces.d/60-ansible-interfaces
  register: ifupdown2
  tags: ['always']
  ignore_errors: true



- include_tasks: ifupdown2.yml
  when: ifupdown2.stat.exists == False

- include_tasks: configure_networking.yml
  when: ifupdown2.stat.exists == False

- include_tasks: networking_config_file.yml
  when: ifupdown2.stat.exists == False


- include_tasks: install_frr.yml
#  when: frr.stat.exists == False

- include_tasks: configure_frr.yml
  tags: ['reconfigure_frr_routing']
  # some logic to run either when there is no FRR file or run if tag has been explicitly passed in
  when: (frr.stat.exists == false) or ("'reconfigure_frr_routing' in ansible_run_tags")

# final reboot
- include_role:
    name: common
    tasks_from: reboot
  when: ifupdown2.stat.exists == False



  
