- include_tasks: ifupdown2.yml
#- include_tasks: cloud_init.yml
- include_tasks: networking_config_file.yml
- include_tasks: install_frr.yml
- include_tasks: configure_frr.yml
#- include_tasks: configure_ifupdown.yml


  
