# initial reboot
#- include_role:
#    name: common
#    tasks_from: reboot
- include_tasks: ifupdown2.yml
- include_tasks: configure_networking.yml
- include_tasks: networking_config_file.yml
- include_tasks: install_frr.yml
- include_tasks: configure_frr.yml

# final reboot
#- include_role:
#    name: common
#    tasks_from: reboot



  
