# only run this one if its specifically tagged with terraform_destroy! (never)
- name: Terraform Destroy
  ansible.builtin.shell:
    cmd: terraform destroy -auto-approve
    chdir: /root/vscode/wizznet-cloud-ansible/terraform/proxmox
  environment:
    PM_PASS: "{{ terraform_password }}"
  #tags: ['never', 'destroy']
  ignore_errors: True