apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-plex
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: PGID
          value: "0"
        - name: PLEX_CLAIM
          value: claim-z3mYkxGqRs_Loqnxbxj1
        - name: PUID
          value: "0"
        image: linuxserver/plex
        imagePullPolicy: Always
        name: plex
        ports:
        - containerPort: 32400
          name: plex32400
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: plexconfig
        - mountPath: /gv1
          name: plexgv1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: plexconfig
        persistentVolumeClaim:
          claimName: plexconfig
      - hostPath:
          path: /gv1
          type: ""
        name: plexgv1

