apiVersion: v1
kind: Service
metadata:
  name: sabnabd-loadbalancer
  namespace: default
spec:
  selector:
    app: sabnzbd
  loadBalancerIP: 10.0.198.3
  ports:
    - port: 32400
      targetPort: 32400
  type: LoadBalancer