apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher
  name: rancher-lb
  namespace: cattle-system
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.0.198.1
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: rancher
  type: LoadBalancer
