apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sabnzbd
  labels:
    app: sabnzbd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - env:
        - name: PGID
          value: "0"
        - name: PUID
          value: "0"
        image: linuxserver/sabnzbd
        imagePullPolicy: Always
        name: sabnzbd
        ports:
        - containerPort: 8080
          name: sabnzbd8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: sabnzbd-config-pvc
        - mountPath: /gv1
          name: sabnzbdgv1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sabnzbd-config-pvc
        persistentVolumeClaim:
          claimName: sabnzbd-config-pvc
      - hostPath:
          path: /gv1
          type: ""
        name: sabnzbdgv1

