apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-loadbalancer
  namespace: default
spec:
  selector:
    app: sabnzbd
  loadBalancerIP: 10.0.198.3
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer