---
# only run this first one with specific tags
- hosts: ovh
  gather_facts: false
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: ovh
      tags: ['ovh_deploy', 'never']

- hosts:
  - baremetal_hosts
  - proxmox_nodes
  - proxmox_qnodes
  - terraform_vms
  - virtual_machines
  - load_balancers
  - plex_servers
  - kubernetes_vms
  - lisk
  gather_facts: false
  any_errors_fatal: true
  become: true
  vars:
    delegate_facts_host: True
  tasks:
    - import_role:
        name: common

- hosts: baremetal_hosts
  gather_facts: true
  become: True
  any_errors_fatal: true
  strategy: free
  tasks:
    - import_role:
        name: day0_pre
      tags: ['day0_pre']
    - import_role:
        name: users
      tags: ['users']
    - import_role:
        name: ssh_keys
      tags: ['ssh_keys']
    - import_role:
        name: install_required_packages
      tags: ['install_required_packages']
    - import_role:
        name: zerotier_networking
      tags: ['zerotier_networking']
    - import_role:
        name: proxmox
      tags: ['proxmox']


   # - import_role:
   #     name: vm_groundwork
   #   tags: ['vm_groundwork']
  # if condition      
  #when: groups.get(my_group_name, []) | length == 0

# break out to clustering role which needs to be linear
- hosts: baremetal_hosts
  gather_facts: true
  become: True
  any_errors_fatal: true
  strategy: linear
  tasks:
    - import_role:
        name: proxmox_clustering
      tags: ['proxmox_clustering']



- hosts: baremetal_hosts
  gather_facts: true
  become: True
  any_errors_fatal: true
  strategy: free
  tasks:
    - import_role:
        name: networking
      tags: ['networking']
    - import_role:
        name: firewall
      tags: ['firewall']
    - import_role:
        name: lxd
      tags: ['lxd']
    - import_role:
        name: storage_configuration
      tags: ['storage_configuration']
    - import_role:
        name: proxmox_vm
      tags: ['proxmox_vm']


#- hosts: terraform_control
#  gather_facts: false
#  become: True
#  any_errors_fatal: true
#  tasks:
#    - import_role:
#        name: terraform
#    #  tags: ['terraform_deploy']