[tool.poetry]
name = "wizzcloud-ansible-lab"
version = "0.1.0"
description = ""
authors = ["JMC"]

[tool.poetry.dependencies]
python = "^3.7"
ansible = "^4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
