- name: Set Hosts File
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
  #when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ hostsfile_entries }}"

# remove the 127.0.1.1 entry
- name: Remove 127.0.1.1
  lineinfile:
    dest: /etc/hosts
    # regexp: '.*{{ item }}$'
    regexp: '127.0.1.1'
    state: absent
    # line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ LOCAL_HOSTNAME }} {{ LOCAL_HOSTNAME }}.{{ LOCAL_DOMAIN_NAME }}"
    # state: present
  #when: hostvars[item].ansible_default_ipv4.address is defined
  #with_items: "{{ groups['dbservers'] }}"

# remove cloud-init access to /etc/hosts
- name: Stop Cloud-init from messing everything up - remove ability to managed /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    # regexp: '.*{{ item }}$'
    regexp: '- update_etc_hosts'
    state: absent
