
  

- name: Linstor peer configuration
  shell: |
    linstor node create p20 {{  linstor.main_address }} --node-type combined
    linstor node create p21 {{  linstor.peer_address }}
  ignore_errors: true

- name: Linstor storage pool - master
  command: |
    linstor storage-pool create zfsthin p20 {{ item.0.name }} {{ linstor.devices.backing_storage }}
  ignore_errors: true

- name: Linstor storage pool - slave
  command: |
    linstor storage-pool create zfsthin p21 {{ item.0.name }} {{ linstor.devices.backing_storage }}
  ignore_errors: true

- name: Linstor resource group
  command: |
    linstor resource-group create {{ item.0.resource_group.name }} --storage-pool {{ item.0.name }} --place-count 2
  ignore_errors: true

- name: Linstor volume group
  command: |
    linstor volume-group create {{ item.0.resource_group.name }}
  ignore_errors: true

- name: Linstor Resource Definition
  command: |
    linstor rd create {{ item.1.name }}
  ignore_errors: true


- name: Linstor volume Definition
  command: |
    linstor vd create {{ item.1.name }} {{ item.1.volume_definition.size }} --storage-pool {{ item.0.name }} -n {{ item.1.volume_definition.volume_number }}
  ignore_errors: true

- name: Linstor resource create
  shell: |
    linstor resource create p20 {{ item.1.name }}
    linstor resource create p21 {{ item.1.name }}
  ignore_errors: true