- include_tasks: glusterfs.yml
- include_tasks: glusterfs_client.yml
- include_tasks: samba.yml
- include_tasks: s3fsfuse.yml
- include_tasks: linstor_install.yml

- include_tasks: linstor_zfs.yml

- include_tasks: linstor_configure.yml
  when: " 'proxmox_master' in group_names "
  loop: "{{ linstor.devices.storage_pool|subelements('resource_definition') }}"
  tags: ['linstor_configure']



  
