- name: Install packages for s3fs fuse
  apt:
    pkg:
      - libfuse-dev
      - fuse
      - build-essential
      - libcurl4-openssl-dev
      - libxml2-dev
      - pkg-config
      - libssl-dev 
      - automake
      - git

- name: Create directory for mounting blackblaze s3fs fuse to
  file:
    path: /backups/backblaze
    state: directory
    owner: root
    
- name: clone repo
  ansible.builtin.git:
    repo: https://github.com/s3fs-fuse/s3fs-fuse
    clone: yes
    dest: /tmp/s3fs-fuse

- name: install s3fs
  shell: |
    cd /tmp/s3fs-fuse
    ./autogen.sh
    ./configure
    make
    make install

- name: symlink binary
  ansible.builtin.file:
    src: /usr/local/bin/s3fs
    dest: /usr/bin
    state: link
    force: no
  ignore_errors: true

- name: Create s3fs backblaze password file
  ansible.builtin.template:
    src: passwd-s3fs.j2
    dest: /etc/passwd-s3fs
    mode: 0600
    owner: root

# clever bit to add a line/block to fstab file but use a template as a basis and add a marker.
- name: Manage fstab file
  blockinfile:
    path: /etc/fstab
    block: "{{  lookup('template', 'baremetal_fstab_s3fs.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for s3fs Mount"
  when: "'baremetal_hosts' in group_names"