- name: Install snap Core
  shell: snap install core

- name: Install LXD via Snap
  shell: snap install lxd

- name: Create zfs storage using LXD wrapper
  shell: |
        /snap/bin/lxc storage create {{ item.name }} zfs source={{ item.name }}
  with_items: '{{ storage.zfs.zpools }}'
  args:
    creates: /zpool1


#- name: LXD create dummy bridge
#  shell: |
#        /snap/bin/lxc launch images:alpine/edge/amd64 alpine1 -s zpool1 -n lxdbr1
#        /snap/bin/lxc config set alpine1 boot.autostart=1
