
- block:
  # Key handling [[[1
  - name: Register if config/private key already exists on target host
    stat:
      path: "{{ wireguard_remote_directory }}/{{ wireguard_interface }}.conf"
    register: wireguard__register_config_file

  - name: Get wg subcommands
    command: "wg --help"
    register: wireguard__register_subcommands
    changed_when: false
    check_mode: no

  - name: Check if wg syncconf subcommand is available
    set_fact:
      wg_syncconf: "{{ 'syncconf:' in wireguard__register_subcommands.stdout }}"
  tags:
    - wg-generate-keys
    - wg-config

- name: Show syncconf subcommand status
  debug:
    var: wg_syncconf

- block:
  - name: Generate WireGuard private key
    command: "wg genkey"
    register: wireguard__register_private_key
    changed_when: false
    tags:
      - wg-generate-keys

  - name: Set private key fact
    set_fact:
      wireguard_private_key: "{{ wireguard__register_private_key.stdout }}"
    tags:
      - wg-generate-keys
  when:
    - not wireguard__register_config_file.stat.exists
    - wireguard_private_key is not defined

- block:
  - name: Read WireGuard config file
    slurp:
      src: "{{ wireguard_remote_directory }}/{{ wireguard_interface }}.conf"
    register: wireguard__register_config
    tags:
      - wg-config

  - name: Set private key fact
    set_fact:
      wireguard_private_key: "{{ wireguard__register_config['content'] | b64decode | regex_findall('PrivateKey = (.*)') | first }}"
    tags:
      - wg-config
  when:
    - wireguard__register_config_file.stat.exists
    - wireguard_private_key is not defined

- name: Derive WireGuard public key
  command: "wg pubkey"
  args:
    stdin: "{{ wireguard_private_key }}"
  register: wireguard__register_public_key
  changed_when: false
  check_mode: no
  tags:
    - wg-config

- name: Set public key fact
  set_fact:
    wireguard__fact_public_key: "{{ wireguard__register_public_key.stdout }}"
  tags:
    - wg-config