
- name: wait for stable quorum
  command: pvecm status
  retries: 10
  delay: 3
  register: status
  until: status.stdout.find("wizzcluster") != -1
  when: "'proxmox_master' in group_names" 

- name: wait for stable quorum
  command: pvecm status
  retries: 10
  delay: 3
  register: status
  until: status.stdout.find("wizzcluster") != -1
  when: "'proxmox_master' not in group_names" 

- name: pve template operations module
  pve_operations:
    func: create_template
    template_ids: "{{ proxmox.host_templates }}"
    zpool_name: "{{ group_storage.zfs.zpools.0.name }}"
    image_name: "{{ proxmox.group_templates.0.vm_image_name }}"
  become: yes
  register: pve_template_result

- name: print var for debugging purposes
  ansible.builtin.debug:
    msg: " {{ pve_template_result.data }} "