# Upgrade the servers via dist-upgrade!
- hosts: 
    - baremetal_hosts
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['update_firewall']
  tasks:
    - import_role:
        name: firewall
        tasks_from: update_before_rules
   #   when: "'dist_upgrade' in ansible_run_tags"
    #  tags: ['update_firewall']
    - import_role:
        name: firewall
        tasks_from: ufw

