# Upgrade the servers via dist-upgrade!
- hosts:
    - baremetal_hosts
    - virtual_machines
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: common
        tasks_from: dist_upgrade
      #   when: "'dist_upgrade' in ansible_run_tags"
      tags: ["dist_upgrade"]

- hosts:
    - docker_hosts
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: common
        tasks_from: install_docker
      #   when: "'install_docker' in ansible_run_tags"
      tags: ["install_docker"]
