# Upgrade the servers via dist-upgrade!
- hosts: 
    - virtual_machines
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: vm_networking
#        tasks_from: dist_upgrade
      tags: ['vm_networking']