# Upgrade the servers via dist-upgrade!
- hosts: 
    - baremetal_hosts
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: proxmox
        tasks_from: proxmox_storage
      tags: ['setup_s3fs']