interfaces:
  bridges:
    evpn:
      - name: evpn100
        ip: 10.0.0.1
        mask: 255.255.255.0
        mtu: 1350
      - name: evpn101
        ip: 10.1.1.1
        mask: 255.255.255.0
        mtu: 1350
    vxlan:
      - name: vxlan100
      - name: vxlan101 
