group_storage:
  zfs:
    zpools:
      - name: zpool1
        datasets:
          proxmox: zpool1/proxmox_vm
          k3s: zpool1/k3s
          gluster: zpool1/gluster
          lizardfs: zpool1/lizardfs
        nodes:
          - p20
          - p21
  gluster:
    volumes:
      - name: gv1
        folder: /gv1



