- name: Linstor Resource Definition
  command: |
    linstor rd create {{ item.1.name }}
  ignore_errors: true

- name: Linstor volume Definition
  command: |
    linstor vd create {{ item.1.name }} {{ item.1.volume_definition.size }} --storage-pool {{ item.0.name }} -n {{ item.1.volume_definition.volume_number }} -m {{ item.1.volume_definition.volume_number }}
  ignore_errors: true

- name: Linstor resource create
  shell: |
    linstor resource create test1 {{ item.1.name }}
  ignore_errors: true