---
- name: Deploy bare metal nodes using ovh API (via custom python exec module)
  ovh_deploy:
    endpoint: "{{ endpoint }}"
    application_key: "{{ application_key }}"
    application_secret: "{{ application_secret }}"
    consumer_key: "{{ consumer_key }}"
    server_inventory: "{{ servers }}"
  register: result


