

- name: check existence of files - frr
  stat:
    path: /etc/frr/frr.conf
  register: frr
  #tags: ["always"]
  ignore_errors: true


- include_tasks: install_frr.yml
#  when: frr.stat.exists == False

- include_tasks: configure_frr.yml
  tags: ["reconfigure_frr_routing"]
  # some logic to run either when there is no FRR file or run if tag has been explicitly passed in
  when: (frr.stat.exists == false) or ("'reconfigure_frr_routing' in ansible_run_tags")


