- name: Re-gather facts
  setup: ~

- name: Create UFW Defaults - Baremetal Hosts
  ansible.builtin.template:
    src: baremetal_hosts/ufw_defaults.j2
    dest: /etc/default/ufw
 # notify: restart ufw
  when: "'baremetal_hosts' in group_names"

- name: Create UFW Defaults - Baremetal Hosts
  ansible.builtin.template:
    src: baremetal_hosts/ufw_before_rules.j2
    dest: /etc/ufw/before.rules
 # notify: restart ufw
  when: "'baremetal_hosts' in group_names"


- name: UFW input rules - ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: "'baremetal_hosts' in group_names"
  register: ufw_output



- name: Allow specific UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: 9993
      proto: udp
    - port: 51820
      proto: udp
    - port: 4242
      proto: udp
  when: "'baremetal_hosts' in group_names"
  register: ufw_output



- name: Allow all in to specific interfaces
  community.general.ufw:
    rule: allow
    interface: "{{ item.interface }}"
    direction: in
  loop:
    - interface: zt+
    - interface: lxdbr+
    - interface: evpn+
    - interface: nebula+
    - interface: br+
    - interface: wg+
  when: "'baremetal_hosts' in group_names"
  register: ufw_output



- name: UFW Flush iptables NAT rules and reload UFW
  shell: |
    iptables -t nat -F && ufw reload
  when: "'baremetal_hosts' in group_names"
  register: ufw_output


#- name: UFW input rules - Baremetal Hosts
#  shell: |
#    ufw allow ssh
#    ufw allow 9993/udp
#    ufw allow 51820/udp
#    ufw allow 4242/udp
#    ufw allow in on zt+
#    ufw allow in on lxdbr+
#    ufw allow in on evpn+
#    ufw allow in on nebula+
#    ufw allow in on br+
#    ufw allow in on wg+
#    ufw allow from 86.29.22.70/32 to any port 8006
#    ufw allow from 10.12.0.0/16 to any port 8006
#    ufw logging off
#    ufw --force enable
#    iptables -t nat -F && ufw reload
#  when: "'baremetal_hosts' in group_names"
#  register: ufw_output


