- name: Re-gather facts
  setup: ~

- name: Create UFW Defaults - Baremetal Hosts
  ansible.builtin.template:
    src: baremetal_hosts/ufw_defaults.j2
    dest: /etc/default/ufw
 # notify: restart ufw
  when: "'baremetal_hosts' in group_names"


- name: Flush rules before adding "before rules"
  command: iptables -F -vt "{{ item }}"
  loop:
    - mangle
    - nat


- name: Create UFW Defaults - Baremetal Hosts
  ansible.builtin.template:
    src: baremetal_hosts/ufw_before_rules.j2
    dest: /etc/ufw/before.rules
 # notify: restart ufw
  when: "'baremetal_hosts' in group_names"




- name: UFW input rules - ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: "'baremetal_hosts' in group_names"
  register: ufw_output
  retries: 5
  delay: 5
  until: ufw_output is succeeded





- name: Allow specific UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: 9993
      proto: udp
    - port: 51820
      proto: udp
    - port: 4242
      proto: udp
  when: "'baremetal_hosts' in group_names"
  register: ufw_output
  retries: 5
  delay: 5
  until: ufw_output is succeeded



- name: Allow all in to specific interfaces
  community.general.ufw:
    rule: allow
    interface: "{{ item.interface }}"
    direction: in
  loop:
    - interface: zt+
    - interface: lxdbr+
    - interface: evpn+
    - interface: nebula+
    - interface: br+
    - interface: wg+
  when: "'baremetal_hosts' in group_names"
  register: ufw_output
  retries: 5
  delay: 5
  until: ufw_output is succeeded


- name: allow proxmox api for terraform
  community.general.ufw:
    rule: allow
    from_ip: 86.29.22.70/32
    to_port: 8006
    proto: tcp
    direction: in
  register: ufw_output
  retries: 5
  delay: 5
  until: ufw_output is succeeded

- name: UFW Flush iptables NAT rules and reload UFW
  shell: |
    iptables -t nat -F && ufw reload
  when: "'baremetal_hosts' in group_names"
  register: ufw_output
  retries: 5
  delay: 5
  until: ufw_output is succeeded

- name: enable UFW
  community.general.ufw:
    state: enabled



