- name: Install required packages
  apt:
    update_cache: true
    pkg:
    - curl
    - sudo
    - nano
    - ufw
    - iftop 
    - iperf3
    - fail2ban
    - molly-guard
    - htop
    - snap
    - conntrack
    - git
    - ifstat
    - iptraf-ng
    - lzop
    - mbuffer
    - pigz 
    - ncdu
    - tree
    - samba
    - cifs-utils
    - mtr-tiny
    - dnsutils
    - mosh
    - frr
    - libpam-google-authenticator
    - cpu-checker
    - snapd 
    - snap 
    - nethogs
    - pv
    - debhelper
    - python3-pip
    - bridge-utils
    - tcpdump
    - parted
    - pkg-config
    - python-pip
    - openvswitch-switch
    - byobu
    - zsh
    - syslog-ng
    - python3-setuptools
