- name: create bridge for portainer
  docker_network:
    name: br-portainer
    state: present
    driver: bridge
    driver_options:
      com.docker.network.driver.mtu: 1300
    ipam_config:
      - subnet: 10.21.67.0/24


- name: Docker container for Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    restart_policy: always
    hostname: portainer
    domainname: '{{ global_domain_name }}'
    dns_servers:
      - 8.8.4.4
      - 1.1.1.1
      - 9.9.9.9
    networks_cli_compatible: true
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
      SUBFOLDER: "/"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: br-portainer
        ipv4_address: 10.21.67.10
# remove the nat ports as this is routed on its own bridge
#    ports:
#      - "8000:8000"
#      - "9000:9000"
    shm_size: 1G
    memory: 2G
    cpus: 1
  register: portainer