global:
  dns_nameservers:
    - 8.8.8.8
    - '{{hostvars["wizz-node-1"].freeipa.ipa_address}}'
    - '{{hostvars["wizz-node-2"].freeipa.ipa_address}}'
    - '{{hostvars["wizz-node-3"].freeipa.ipa_address}}'
    - 1.1.1.1
    - 9.9.9.9
    - 8.8.4.4
frr_version: frr-stable
global_domain_name: wizznet.co.uk
