- name: Terraform Deploy
  ansible.builtin.shell:
    cmd: terraform apply -auto-approve
    chdir: /root/vscode/wizznet-cloud-ansible/terraform/proxmox
  environment:
    PM_PASS: "{{ terraform_password }}"
  tags: ['deploy']
  ignore_errors: True

