- name: Terraform Deploy
  community.general.terraform:
    project_path: /root/vscode/wizznet-cloud-ansible/terraform/proxmox
    state: present
  environment:
    PM_PASS: "{{ terraform_password }}"
    TF_CLI_ARGS_apply: "-parallelism=10"


#- name: Terraform Deploy
#  ansible.builtin.shell:
#    cmd: terraform apply -auto-approve
#    chdir: /root/vscode/wizznet-cloud-ansible/terraform/proxmox
#  environment:
#    PM_PASS: "{{ terraform_password }}"
#  tags: ['deploy']
#  ignore_errors: True



