netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        mtu: 1350
      eth1:
        mtu: 1350
      eth2:
        mtu: 1350
      eth3:
        mtu: 1350
  #   enp0s3:
  #       dhcp4: true
  #     enp0s8:
  #       addresses:
  #         - 192.168.250.10/24
  #         - 192.168.250.11/24
  #       nameservers:
  #         addresses:
  #           - 10.0.2.3
  #           - 8.8.8.8
  #           - 8.8.4.4
  #         search:
  #           # Custom variable
  #           - "{{ netplan_pri_domain }}"
  #       gateway4: 192.168.250.1
  #       optional: true
  #       routes:
  #         - to: 0.0.0.0/0
  #           via: 9.9.9.9
  #           on-link: true
  #         - to: 192.168.5.0/24
  #           via: 192.168.5.1
  #           table: 102
  #       routing-policy:
  #         - from: 192.168.5.0/24
  #           table: 102
  #     lo:
  #       match:
  #         name: lo
  #       addresses: [7.7.7.7/32]
  #   wifis:
  #     wlp2s0b1:
  #       dhcp4: no
  #       dhcp6: no
  #       addresses: [192.168.0.21/24]
  #       gateway4: 192.168.0.1
  #       access-points:
  #         "network_ssid_name":
  #           password: "**********"
  #   bonds:
  #     bond0:
  #       dhcp4: yes
  #       interfaces:
  #         - enp0s3
  #         - enp4s0
  #       parameters:
  #         # modes can be one of balance-rr, active-backup, balance-xor, broadcast,
  #         # 802.3ad, balance-tlb, and balance-alb.
  #         mode: active-backup
  #         primary: enp0s3
  #   bridges:
  #     # br0:
  #     #   dhcp4: yes
  #     #   interfaces:
  #     #     - enp0s3
  #     br0:
  #       addresses: [10.3.99.25/24]
  #       interfaces: [vlan15]
  #   vlans:
  #     vlan15:
  #       accept-ra: no
  #       id: 15
  #       link: enp0s25
