# install zfsutils-linux
- name: Install linux headers
  apt:
    pkg:
      - "linux-headers-{{ ansible_kernel }}"

- name: Install useful zfs packages
  apt:
    update_cache: true
    pkg:
    - zfsutils-linux 
    - zfs-dkms 
    - dpkg-dev 
    - linux-image-amd64
  ignore_errors: true

# modprobe zfs kernel module
- name: zfs
  community.general.modprobe:
    name: zfs
    state: present
  ignore_errors: true
