# warning this will wipe your current pools!

- name: Create zpools - OVH
  command: zpool create zpool1 mirror {{ item.disks[0] }} {{ item.disks[1] }} -f
  with_items: '{{ storage.zfs.zpools }}'
  args:
    creates: /zpool1
  when: "'ovh_nodes' in group_names"

- name: Create zpools - Test / Eve-NG Nodes
  command: zpool create zpool1 {{ item.disks[0] }} -f
  with_items: '{{ storage.zfs.zpools }}'
  args:
    creates: /zpool1
  when: "'ovh_nodes' not in group_names"

- name: Create ZFS Datasets 
  community.general.zfs:
    name: "{{ item.value }}"
    state: present
  #with_items: "{{ storage.zfs.zpools[0].datasets | dictsort }}"
  with_items: "{{ group_storage.zfs.zpools[0].datasets | dict2items }}"
  ignore_errors: true