# install zfsutils-linux
- name: Install useful zfs packages
  apt:
    update_cache: true
    pkg:
    - zfsutils-linux 

# modprobe zfs kernel module
- name: zfs
  community.general.modprobe:
    name: zfs
    state: present

# unmount - get drive list
- name: unmount
  parted:
    device: "{{ item }}"
    unit: MiB
  register: info
  loop: "{{ storage.zfs.zpools[0].disks }}"

# unmount - unmount drives
- name: debug stuff
  debug:
    msg: "{{ item.0.disk.dev }} {{ item.1.num }}"
  loop: "{{ info.results | subelements('partitions') }}"

# unmount current drives
- name: wipe current drives
  command: "umount {{ item }}"
  loop: "{{ storage.zfs.zpools[0].disks }}"



# warning this will wipe your current pools!

- name: Create zpools - OVH
  command: zpool create zpool1 mirror {{ item.disks[0] }} {{ item.disks[1] }} -f
  with_items: '{{ storage.zfs.zpools }}'
  args:
    creates: /zpool1
  when: "'ovh_nodes' in group_names"

- name: Create zpools - Test / Eve-NG Nodes
  command: zpool create zpool1 {{ item.disks[0] }} -f
  with_items: '{{ storage.zfs.zpools }}'
  args:
    creates: /zpool1
  when: "'ovh_nodes' not in group_names"

- name: Create ZFS Datasets 
  community.general.zfs:
    name: "{{ item.value }}"
    state: present
  #with_items: "{{ storage.zfs.zpools[0].datasets | dictsort }}"
  with_items: "{{ group_storage.zfs.zpools[0].datasets | dict2items }}"
  ignore_errors: true