# create template
- name: Set teleport server config
  template:
    src: templates/server/teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - "restart teleport"

- name: start teleport
  service:
    name: teleport
    state: started
    enabled: yes
