# remove /var/lib/teleport
- name: Fetch the certificate from nebula cert authority   
  file: 
    path: /var/lib/teleport
    state: absent
  become: true

# create template
- name: Set teleport proxy config
  template:
    src: templates/proxy/teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - "restart teleport"


