# has to be run in blocks to keep the registered variable associated
- block:
  - name: run node command - for type proxy
    command: tctl nodes add --roles node,proxy
    register: tctl_output
    delegate_to: teleport.wizznet.co.uk
    
  
  - name: set fact - get stdout
    set_fact:
      tctl: "{{tctl_output}}"

  when: "'teleport_proxy_servers' in group_names"

# has to be run in blocks
- block: 
  - name: run node command - for type client
    command: tctl nodes add --roles node
    register: tctl_output
    delegate_to: teleport.wizznet.co.uk
    
  
  - name: set fact - get stdout
    set_fact:
      tctl: "{{tctl_output}}"
  when: "'teleport_clients' in group_names"


- name: print output 
  debug:
    msg: "{{tctl}}"


- name: set fact - get token
  set_fact:
  # Get string after --token= but then ignore end white space - also double backslash to escape character 
    teleport_token: "{{ tctl | regex_findall('--token=([^\\s]+)') | first }}"

- name: set fact - get ca-pin
  set_fact:
  # Get string after ---ca-pin=  but then ignore end white space - also double backslash to escape character 
    teleport_ca_pin: "{{ tctl | regex_findall('--ca-pin=([^\\s]+)') | first }}"
  
- name: print var
  debug:
    msg: "{{teleport_token}}"
  
    
- name: print var
  debug:
    msg: "{{teleport_ca_pin}}"
    
