- hosts: 
    - openvpn_servers
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: install_required_packages
        tasks_from: install_baseline_packages_vm
  # install FRR on auth server as it is advertising anycast loopback to the host with eBGP
    - include_role: # loop through to pull in multiple tasks (only works with include)
        name: networking
        tasks_from: '{{ item }}'
      loop:
        - install_frr
        - configure_frr_anycast_vm

  tags: ['configure_frr_pritunl']
