#- name: Set Hosts File
#  lineinfile:
#    dest: /etc/hosts
#    line: "{{ item }}"
#    state: present
#  with_items: "{{ hostsfile_entries }}"

- name: Set Hosts File
  blockinfile:
    path: /etc/hosts
    block: "{{  lookup('template', 'hosts.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for hostsfile dns entries"

# remove cloud-init access to /etc/hosts for every device
- name: Stop Cloud-init from messing everything up - remove ability to managed /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    # regexp: '.*{{ item }}$'
    regexp: '- update_etc_hosts'
    state: absent

- name: Delete resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Replace resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: touch

- name: Set Global DNS resolvers 
  blockinfile:
    path: /etc/resolv.conf
    block: "{{  lookup('template', 'resolv.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for resolver dns nameservers"

## TEST TO SEE IF FULLY QUALIFIED CAN BE PRESERVED
#- name: Stop Cloud-init from messing everything up - remove ability to managed /etc/hosts
#  lineinfile:
#    dest: /etc/cloud/cloud.cfg
#    # regexp: '.*{{ item }}$'
#    regexp: '- update_etc_hosts'
#    state: absent