- name: Set Hosts File
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
  with_items: "{{ hostsfile_entries }}"

# remove cloud-init access to /etc/hosts for every device
- name: Stop Cloud-init from messing everything up - remove ability to managed /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    # regexp: '.*{{ item }}$'
    regexp: '- update_etc_hosts'
    state: absent