---

# wait for vm up and ready
- name: wait for vm up and ready
  command: whoami
  retries: 60
  delay: 3
  register: result
  until: result is succeeded

- name: Configuring Netplan
  template:
    src: netplan.config.yaml.j2
    dest: "{{ netplan_config_file }}"
  become: true
  when: netplan_configuration != []
  notify: netplan generate config