
- name: Docker container for freeipa replica - Hetzner cloud
  docker_container:
    name: '{{ freeipa.name }}'
    image: '{{ ipa_container_image }}'
    restart_policy: always
    hostname: '{{ freeipa.name }}'
    domainname: '{{ ipa_domain_name }}'
    dns_servers:
      - "{{ hostvars['p20'].freeipa.ipa_address }}"
      - "{{ hostvars['p21'].freeipa.ipa_address }}"
      - 8.8.4.4
      - 1.1.1.1
      - 9.9.9.9
    etc_hosts:
      ipa3.wizznet.co.uk: '{{ freeipa.ipa_address }}'
    networks_cli_compatible: true
    env:
      IPA_SERVER_HOSTNAME: '{{ freeipa.ipa_hostname }}'
      IPA_SERVER_IP: '{{ freeipa.ipa_address }}'
      DNS: "{{ hostvars['p20'].freeipa.ipa_address }}"
#      PASSWORD: password
    command:
      - ipa-replica-install
      - "--domain={{ ipa_domain_name }}"
      - "--ip-address={{ freeipa.ipa_address }}"
      - --server=ipa.wizznet.co.uk
      - "--admin-password={{ipa_admin_password}}"
      - --no-dnssec-validation
      - --no-host-dns
      - --setup-dns
      - --setup-ca
      - --forwarder=9.9.9.9
      - --forwarder=1.1.1.1
      - --forwarder=8.8.4.4
      - --allow-zone-overlap
      - --unattended
 #     - --skip-conncheck  # note that this is only used because the hetz cloud server is slow and it fails otherwise.
    volumes:
      - /docker/ipa_ansible/data:/data
      - /docker/ipa_ansible/logs:/var/logs
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    capabilities:
      - SYS_TIME
    networks:
      - name: '{{ ipa_bridge }}'
        ipv4_address: '{{ freeipa.ipa_address }}'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    memory: 2G
    cpus: 1