
- name: Docker container for freeipa replica
  docker_container:
    name: '{{ freeipa.name }}'
    image: '{{ ipa_container_image }}'
    restart_policy: always
    hostname: '{{ freeipa.name }}'
    domainname: '{{ ipa_domain_name }}'
    dns_servers:
      - "{{ hostvars['p20'].freeipa.ipa_address }}"
      - 8.8.4.4
      - 1.1.1.1
      - 9.9.9.9
    etc_hosts:
      ipa2.wizznet.co.uk: '{{ freeipa.ipa_address }}'
    networks_cli_compatible: true
    env:
      IPA_SERVER_HOSTNAME: '{{ freeipa.ipa_hostname }}'
      IPA_SERVER_IP: '{{ freeipa.ipa_address }}'
      DNS: "{{ hostvars['p20'].freeipa.ipa_address }}"
#      PASSWORD: password
    command:
      - ipa-replica-install
      - "--domain={{ ipa_domain_name }}"
      - "--ip-address={{ freeipa.ipa_address }}"
      - --server=ipa.wizznet.co.uk
      - "--admin-password={{ipa_admin_password}}"
      - --no-dnssec-validation
      - --no-host-dns
      - --setup-dns
      - --setup-ca
      - --forwarder=9.9.9.9
      - --forwarder=1.1.1.1
      - --forwarder=8.8.4.4
      - --allow-zone-overlap
      - --unattended
  #    - --force-join
    volumes:
      - /docker/ipa_ansible/data:/data
      - /docker/ipa_ansible/logs:/var/logs
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    capabilities:
      - SYS_TIME
    networks:
      - name: '{{ ipa_bridge }}'
        ipv4_address: '{{ freeipa.ipa_address }}'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
  register: ipa_replica



- name: Wait for IPA Replica
  wait_for:
    host: "{{ freeipa.ipa_address }}"
    port: 443
    state: started
    connect_timeout: 1
    timeout: 30
  register: ipa_replica_running
  until: ipa_replica_running is success
  retries: 25