# Upgrade the servers via dist-upgrade!
- hosts: 
    - baremetal_servers
    - virtual_machines
  gather_facts: true
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: common
        tasks_from: dist_upgrade
      tags: ['dist_upgrade']