nebula_port: 4242
nebula_external_addr: 188.165.235.210

nebula_ip: "10.140.140.21"

# per host inbound rules
nebula_inbound_rules: |
 
  - port: 443
    proto: tcp
    host: any

  - port: 80
    proto: tcp
    host: any


nebula_outbound_rules: |
  - port: any
    proto: any
    host: any