nebula_port: 4242
nebula_external_addr: 51.77.116.79

nebula_ip: "10.140.140.20"

# per host inbound rules
nebula_inbound_rules: |
  - port: 443
    proto: tcp
    host: any

  - port: 80
    proto: tcp
    host: any

  - port: any
    proto: icmp
    host: any

nebula_outbound_rules: |
  - port: any
    proto: any
    host: any