# only gather facts during the run as otherwise they would have tried to be gathered before vm instanciation
- name: Gathering facts
  setup:

- include_tasks: filesystem_changes.yml

- include_tasks: miscellaneous.yml

- include_tasks: pre_checks.yml

- include_tasks: install_packages.yml
    
- include_tasks: k3s.yml
 # when: kube_installed.rc == 2
  ignore_errors: true

- include_tasks: install_rancher.yml
  when: " 'kube1' in inventory_hostname "

- include_tasks: metallb.yml
  when: " 'kube1' in inventory_hostname "

- include_tasks: glusterfs.yml


