# https://get.gravitational.com/teleport_6.0.2_amd64.deb

# This is for deb version amd64 only
gravitational_teleport_version: "6.0.2"
gravitational_arch: amd64
gravitational_url: https://get.gravitational.com/
gravitational_download_url: "{{gravitational_url}}teleport_{{gravitational_teleport_version}}_{{gravitational_arch}}.deb"
gravitational_teleport_cluster_name: wizznet
